// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far an acquisition has got.
 *
 * Counted in sectors rather than bytes because that is the unit a medium
 * fails in: the sweep skips a failing region and the refinement revisits
 * it one sector at a time, and both are reported against the same
 * denominator.
 */
export type AcquireProgress = { 
/**
 * `sweep` for the sequential pass, `refine` for the sector-by-sector
 * revisit of what the sweep skipped.
 */
pass: string, 
/**
 * Sectors this pass has covered.
 */
done: number, 
/**
 * Sectors this pass has to cover.
 */
total: number, };

/**
 * What a started acquisition tells its client before it copies anything.
 */
export type AcquireStarted = { 
/**
 * One line naming the medium being copied.
 */
source: string, 
/**
 * Path of the raw image being written.
 */
to: string, 
/**
 * Sectors the medium holds, so a client has a denominator from the
 * first frame.
 */
sectors: number, };

/**
 * What an acquisition produced.
 *
 * `recovered` is never presented as the whole medium when it is not:
 * whatever stayed unreadable is zero-filled in the image and counted here,
 * because those zeroes are placeholders and a client that showed them as
 * data would be reporting bytes that were never read
 * (`A-CONFIDENCE-HONEST`).
 */
export type Acquired = { 
/**
 * Path of the image that was written.
 */
image: string, 
/**
 * Sectors the medium holds.
 */
sectors: number, 
/**
 * Sectors actually read off the medium and into the image.
 */
recovered: number, 
/**
 * Runs of sectors that stayed unreadable after both passes.
 */
unreadableRegions: number, 
/**
 * Sectors the run never tried, because it was stopped before reaching
 * them.
 *
 * Never folded into `unreadable_regions`: that is what the *medium*
 * refused, and a run its operator stopped says nothing about the
 * medium. Merging the two would turn a cancelled copy into a report of
 * a damaged disk (`A-CONFIDENCE-HONEST`).
 */
notAttempted: number, 
/**
 * Whether the run was stopped before it covered the medium.
 */
stoppedEarly: boolean, 
/**
 * Whether every sector was read.
 */
complete: boolean, };

/**
 * One recovered artifact, as a results view needs it.
 *
 * Every field is copied from the manifest. A client that recomputes any
 * of them is doing recovery work in a presentation layer
 * (`A-SHELL-NO-DOMAIN`).
 */
export type Artifact = { 
/**
 * File name inside the session directory, absent when the run was
 * told to leave this artifact unwritten. Its extents and digest are
 * recorded either way.
 */
name: string | null, 
/**
 * SHA-256 of the artifact bytes, lowercase hex.
 */
sha256: string, 
/**
 * Recovery stage that produced it.
 */
stage: string, 
/**
 * Image format it validated as.
 */
format: string, 
/**
 * Evidence tier, as its canonical display name.
 */
confidence: string, 
/**
 * What was actually recovered and stored, in bytes.
 */
length: number, 
/**
 * Length the source metadata claimed, when it said one.
 */
expectedLength: number | null, 
/**
 * Bytes the metadata expected that were not recovered.
 */
missingBytes: number | null, 
/**
 * Every source extent it was assembled from, in file order.
 */
extents: Array<Extent>, 
/**
 * Creation time from metadata, seconds since the Unix epoch.
 */
createdUnix: number | null, 
/**
 * Modification time from metadata, seconds since the Unix epoch.
 */
modifiedUnix: number | null, 
/**
 * Name recovered from filesystem metadata, when one survived.
 */
recoveredName: string | null, 
/**
 * Where the artifact stands in a list, by the evidence it carries:
 * `camera-named`, `dated`, `photograph-sized`, `unremarkable` or
 * `cache-neighbour`. A sort key the engine derived; nothing is hidden
 * by it and a client must not recompute it (`A-SHELL-NO-DOMAIN`).
 */
standing: string | null, 
/**
 * Decoded pixel width, when the artifact decoded.
 */
width: number | null, 
/**
 * Decoded pixel height, when the artifact decoded.
 */
height: number | null, 
/**
 * Camera that took the picture, as recorded: make and model joined.
 */
camera: string | null, 
/**
 * When the picture was taken, as EXIF stores it.
 */
taken: string | null, 
/**
 * How many same-sized neighbours it was found among, when it sat in a
 * run of them — the layout a thumbnail cache has.
 */
sameSizeNeighbours: number | null, 
/**
 * Triage label, when it was scored.
 */
triageLabel: string | null, 
/**
 * The property that settled the label, when there is one.
 */
triageDecidedBy: string | null, 
/**
 * SHA-256 of the artifact this one is a near-duplicate of. Both stay.
 */
nearDuplicateOf: string | null, 
/**
 * Preview path relative to the session directory, when one exists.
 */
preview: string | null, };

/**
 * One medium a scan can be pointed at.
 */
export type Device = { 
/**
 * Path to open it by.
 */
path: string, 
/**
 * `disk` or `partition`.
 */
kind: string, 
/**
 * Capacity in bytes, when the platform reported one without opening
 * the device.
 */
capacityBytes: number | null, 
/**
 * What kind of medium the platform says it is.
 */
class: string, 
/**
 * Whether the medium reports TRIM enabled: `enabled`, `disabled` or
 * `unknown`.
 */
trim: string, 
/**
 * Model or product string, when the platform offers one.
 */
model: string | null, 
/**
 * Where the operating system currently has it mounted, if anywhere,
 * already rendered for display.
 */
mounts: Array<string>, 
/**
 * Whether any mount of this medium is writable, so the bytes can
 * change underneath a scan.
 */
writableMount: boolean, };

/**
 * What an export produced.
 */
export type Exported = { 
/**
 * Artifacts copied and verified.
 */
copied: number, 
/**
 * Preview files copied alongside them.
 */
previews: number, 
/**
 * Artifacts whose stored bytes no longer reproduce the manifest's
 * digest, and were therefore not copied.
 */
tampered: Array<string>, 
/**
 * Artifacts recorded in the manifest whose file is missing.
 */
missing: Array<string>, };

/**
 * A byte range, absolute in the medium.
 */
export type Extent = { 
/**
 * Offset of the range's first byte.
 */
offset: number, 
/**
 * Range length in bytes.
 */
length: number, };

/**
 * One page of a session's artifacts, strongest evidence first.
 */
export type Gallery = { 
/**
 * Artifacts on this page, already ordered by the engine.
 */
artifacts: Array<Artifact>, 
/**
 * Artifacts the filter admits across the whole session, so a client
 * can page without asking twice.
 */
total: number, 
/**
 * Artifacts the session recorded in all, whatever the filter.
 */
recorded: number, 
/**
 * Subdirectory holding previews, relative to the session.
 */
previewDir: string, };

/**
 * What the engine answers a handshake with.
 *
 * A client that does not recognise [`Hello::schema`] must stop rather
 * than guess: the two processes are versioned separately and a field
 * silently missing is the worst way to find that out.
 */
export type Hello = { 
/**
 * Wire-format version, [`crate::SCHEMA_VERSION`].
 */
schema: number, 
/**
 * Version of the `argos` binary answering.
 */
toolVersion: string, };

/**
 * What `devices.list` answers.
 */
export type Inventory = { 
/**
 * Media, whole disks first.
 */
devices: Array<Device>, 
/**
 * Shadow copies, empty on platforms without them.
 */
shadowCopies: Array<ShadowCopy>, };

/**
 * What a scan is doing, emitted per chunk of work rather than per
 * candidate (`A-EVENTS-NOT-POLLING`).
 *
 * `done` and `total` are counted in `unit`. A stage that reads the medium
 * counts bytes; one that examines candidates or labels artifacts counts
 * those, and saying which is what stops a candidate count being read as a
 * byte count.
 */
export type Progress = { 
/**
 * Stage reporting progress.
 */
stage: string, 
/**
 * `bytes` or `items`.
 */
unit: string, 
/**
 * Work processed so far.
 */
done: number, 
/**
 * Work the stage expects to cover, zero when not known ahead.
 */
total: number, };

/**
 * Everything a session directory holds, read back from its manifest.
 */
export type Results = { 
/**
 * Version of the tool that produced the session.
 */
toolVersion: string, 
/**
 * Description of the scanned source.
 */
source: string, 
/**
 * How the run ended: `finished`, `cancelled` or `failed`.
 */
state: string, 
/**
 * Signature hits that failed validation and were not recovered.
 */
rejectedCandidates: number, 
/**
 * Byte ranges the medium could not read.
 */
unreadable: Array<Extent>, 
/**
 * How triage ran, when the session says.
 */
triage: Triage | null, 
/**
 * One entry per recovered artifact, in manifest order.
 */
artifacts: Array<Artifact>, };

/**
 * Which recovery stages a scan runs, and what it annotates.
 */
export type ScanRequest = { 
/**
 * Raw image file or block device to scan.
 */
source: string, 
/**
 * Directory receiving recovered files and the manifest.
 */
out: string, 
/**
 * Worker threads; the machine's available parallelism when absent.
 */
jobs: number | null, 
/**
 * Recover from filesystem metadata.
 */
filesystem: boolean, 
/**
 * Carve the full surface.
 */
carving: boolean, 
/**
 * Reassemble images the medium stored in pieces.
 */
reassembly: boolean, 
/**
 * Label artifacts photograph vs synthetic asset.
 */
triage: boolean, 
/**
 * Smallest long side, in pixels, an image is written to disk for.
 * Absent takes the engine's default; zero writes everything.
 * Whatever is not written is still examined, hashed and recorded
 * with its extents and its dimensions.
 */
minLongSide: number | null, 
/**
 * Render a preview of every artifact that decodes.
 */
previews: boolean, 
/**
 * How long reassembly may search, in seconds. Absent takes the
 * engine's own budget; zero searches every candidate however long it
 * takes.
 *
 * Reassembly is the one stage that reaches a ceiling and stops without
 * finishing, and the report says so rather than implying the medium
 * held nothing more. A client that cannot set this cannot ask for the
 * longer search that ceiling exists to bound.
 */
reassemblyBudgetSeconds: number | null, };

/**
 * What a started scan tells its client before it produces anything.
 */
export type ScanStarted = { 
/**
 * One line naming the source, as recorded in the manifest.
 */
source: string, 
/**
 * Directory the session is being written into.
 */
out: string, 
/**
 * Subdirectory of `out` holding previews. A viewer is given access to
 * this and nothing else of the session.
 */
previewDir: string, };

/**
 * A shadow copy this machine holds.
 */
export type ShadowCopy = { 
/**
 * Device path to open it by.
 */
path: string, 
/**
 * The snapshot's index in the object namespace.
 */
index: number, };

/**
 * A stage began.
 *
 * Sent for every stage, including one that will report no progress at
 * all, because a client that hears nothing between two stages cannot tell
 * work from a stall.
 */
export type StageBegan = { 
/**
 * Stage that began.
 */
stage: string, 
/**
 * `bytes` or `items`.
 */
unit: string, 
/**
 * Work the stage expects to cover, zero when not known ahead.
 */
total: number, };

/**
 * A stage ended, having produced this many results.
 */
export type StageDone = { 
/**
 * Stage that ended.
 */
stage: string, 
/**
 * Findings the stage contributed.
 */
findings: number, };

/**
 * A run changed lifecycle state.
 */
export type State = { 
/**
 * `running`, `paused`, `cancelled` or `finished`.
 */
state: string, };

/**
 * What a scan has actually recovered so far, as of one stored artifact.
 *
 * Both figures describe artifacts **stored** — never candidates seen. A
 * signature hit that has not passed its format's state machine is not a
 * recovery, and a display that counted one would overstate the result
 * (`A-CONFIDENCE-HONEST`).
 */
export type Stored = { 
/**
 * Artifacts handed to the sink so far.
 */
artifacts: number, 
/**
 * Sum of their lengths in bytes.
 */
bytes: number, };

/**
 * The account of a finished run, in the figures a display shows.
 *
 * Deliberately not [`Results`]. A run over a system disk recovers tens of
 * thousands of artifacts, and sending every record so a client can count
 * them is megabytes of JSON to produce three numbers — serialized here,
 * parsed there, and re-materialized as objects on whatever thread draws
 * the window. That is a client stopped for seconds at the exact moment
 * the scan succeeds.
 *
 * A client that wants the records asks for them with `scan.results`, once
 * and on purpose. The engine counts; the client is told.
 */
export type Summary = { 
/**
 * How the run ended: `finished`, `cancelled` or `failed`.
 */
state: string, 
/**
 * Description of the scanned source.
 */
source: string, 
/**
 * Artifacts written to the output directory.
 *
 * Never the size of the manifest: a run asked to leave synthetic
 * assets unwritten records every one of them, and counting those here
 * would report as recovered what is not in the directory
 * (`A-CONFIDENCE-HONEST`). They are counted by
 * [`Summary::omitted`] instead.
 */
artifacts: number, 
/**
 * Their total length in bytes.
 */
bytes: number, 
/**
 * Artifacts recorded in the manifest but deliberately not written.
 */
omitted: number, 
/**
 * Signature hits that failed validation and were not recovered.
 */
rejectedCandidates: number, 
/**
 * Regions the medium could not read, and their total length.
 */
unreadableRegions: number, unreadableBytes: number, 
/**
 * The session directory, which is where the records are.
 */
session: string, 
/**
 * How triage ran, when the session says.
 */
triage: Triage | null, };

/**
 * How triage ran over a session.
 */
export type Triage = { 
/**
 * `scored` when a model ran, `disabled` when it did not.
 */
status: string, 
/**
 * Why triage did not run, when it did not.
 */
disabledReason: string | null, 
/**
 * Version of the model that scored the session.
 */
modelVersion: string | null, 
/**
 * Artifacts that received a score.
 */
scored: number, 
/**
 * Artifacts triage saw but could not score.
 */
unscored: number, 
/**
 * Whether the classifier failed mid-run.
 */
degraded: boolean, };

/**
 * How much of the medium refused to be read, as a running total.
 *
 * A count rather than one message per region: a failing disk produces
 * them faster than any client can draw them, and what a client needs is
 * how much was lost. The regions themselves are in the manifest, which is
 * where a record of damage belongs.
 */
export type Unreadable = { 
/**
 * Regions the medium refused so far.
 */
regions: number, 
/**
 * Their total length in bytes.
 */
bytes: number, };

/**
 * Something the user should know that is not progress: a mounted medium,
 * a partition-only scan, a disabled classifier.
 */
export type Warning = { 
/**
 * The message, already written for a person to read.
 */
text: string, };
